server:
  port: 8080

spring:
  application:
    name: booking-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airline_aggregator}
    username: ${SPRING_DATASOURCE_USERNAME:airline_user}
    password: ${SPRING_DATASOURCE_PASSWORD:airline_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

# External service URLs
external:
  payment-service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8083}

# Booking configuration
booking:
  expiry-minutes: 15
  max-passengers: 9

logging:
  level:
    com.airlineaggregator: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 